global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - user-service:8081
          - ticket-service:8082
          - notification-service:8083
          - document-service:8084