spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: ticket-service
  kafka:
    consumer:
      group-id: ${spring.application.name}  # ← Ajoutez cette ligne